// backend/config/boards.js

const boards = [
  {
    id: "random",
    name: "Random",
    description: "Anything and Everything",
    nsfw: true,
    thread_ids_enabled: true,
    country_flags_enabled: true,
  },
  {
    id: "politics",
    name: "Politics",
    description: "Politics and Current Events",
    nsfw: true,
    thread_ids_enabled: true,
    country_flags_enabled: true,
  },
  {
    id: "movies",
    name: "Movies",
    description: "Film and Television",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "gaming",
    name: "Gaming",
    description: "Video Games",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "anime",
    name: "Anime",
    description: "Anime and Manga",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "business",
    name: "Business",
    description: "Business, Finance, Cryptocurrency, Economics, and Investing",
    nsfw: false,
    thread_ids_enabled: true,
    country_flags_enabled: true,
  },
  {
    id: "diy",
    name: "Do It Yourself",
    description: "Hobbies, Home Improvement, Car Repair, and Crafts",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "sports",
    name: "Sports",
    description: "Football, Basketball, Baseball, and More",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: true,
  },
  /*
  {
    id: "tech",
    name: "Technology",
    description: "Technology Discussion",
    nsfw: false,
    thread_ids_enabled: true,
    country_flags_enabled: false,
  },
  { 
    id: "music", 
    name: "Music", 
    description: "Music Discussion", 
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "art",
    name: "Art",
    description: "Art and Design Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "literature",
    name: "Literature",
    description: "Book and Writing Discussion",
    nsfw: false,
    thread_ids_enabled: true,
    country_flags_enabled: false,
  },
  {
    id: "fitness",
    name: "Fitness",
    description: "Fitness and Health Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "food",
    name: "Food",
    description: "Cooking and Culinary Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },
  {
    id: "travel",
    name: "Travel",
    description: "Travel and Adventure Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: true,
  },
  {
    id: "science",
    name: "Science",
    description: "Science Discussion",
    nsfw: false,
    thread_ids_enabled: true,
    country_flags_enabled: false,
  },
  {
    id: "philosophy",
    name: "Philosophy",
    description: "Philosophy Discussion",
    nsfw: false,
    thread_ids_enabled: true,
    country_flags_enabled: false,
  },
  {
    id: "history",
    name: "History",
    description: "History Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: true,
  },
  {
    id: "weapons",
    name: "Weapons",
    description: "Weapons and Military Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: true,
  },
  {
    id: "cars",
    name: "Cars",
    description: "Cars and Transportation Discussion",
    nsfw: false,
    thread_ids_enabled: false,
    country_flags_enabled: false,
  },*/
  // Add more boards as needed
];

module.exports = boards;
